apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-file-server.configName" . }}
  namespace: {{ include "simple-file-server.namespace" . }}
  labels:
{{ include "simple-file-server.labels" . | indent 4 }}
data:
  PORT: "{{ .Values.config.port }}"
  LOG_PATH: "{{ .Values.config.logPath }}"
  UPLOAD_DIR: "{{ .Values.config.uploadDir }}"
