{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-file-server.serviceAccountName" . }}
  namespace: {{ include "simple-file-server.namespace" . }}
  labels:
{{ include "simple-file-server.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
