apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-file-server.fullname" . }}-svc
  namespace: {{ include "simple-file-server.namespace" . }}
  labels:
{{ include "simple-file-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "simple-file-server.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
